version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./socialmedia-backend/Dockerfile.dev
    expose:
      - "4000"
    volumes:
      - ./socialmedia-backend:/app
      - /app/node_modules
      - /home/vava/Programming/Brototype/boarding_machine_task/shared:/app/shared:rw
    depends_on:
      - mongo
      - redis
    env_file:
      - ./socialmedia-backend/.env
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
