services:
  api:
    build:
      context: ./socialmedia-backend
      dockerfile: ./Dockerfile.production
    ports:
      - "4000"
    # volumes:
    #   - ./socialmedia-backend:/app
    #   - /app/node_modules
    #   - /home/vava/Programming/Brototype/boarding_machine_task/shared:/app/shared:rw
    # depends_on:
    #   - mongo
    env_file:
      - ./socialmedia-backend/.env
    # command: sh -c "npm run dev"
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
