services:
  api:
    build:
      context: .
      dockerfile: ./socialmedia-backend/Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./socialmedia-backend:/app
      - /app/node_modules
      - /home/vava/Programming/Brototype/boarding_machine_task/shared:/shared:rw
    depends_on:
      - mongo
      - redis
    env_file:
      - ./socialmedia-backend/.env
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
