FROM node:18

WORKDIR /app
# there is no lock here so check if lock is necessary
COPY ./package.json ../package-lock.json  ./
RUN npm install --omit=optional

EXPOSE 4000

COPY . .

CMD ["npm", "run", "dev"]
